name: web_game
description: Jumping ball
publish_to: 'none'

version: 1.1.1+6

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.2
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.8.1
  firebase_core: ^2.14.0
  http: ^1.0.0
  google_sign_in: ^6.1.0
  google_mobile_ads:
    git:
      url: https://github.com/kBrahman/googleads-mobile-flutter.git
      path: packages/google_mobile_ads


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1

flutter_launcher_icons:
  android: "ball"
  ios: true
  image_path: "assets/ball.png"

flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ball.png
    - assets/ball_ios.png