// ignore_for_file: avoid_print, constant_identifier_names

const NAME = 'name';
const COLLECTION_LEADERBOARD = 'leaderboard';
const SCORE_BEST = 'score';
const FLAG = 'flag';
const ID = 'id';
const COUNTRY = 'country';
const TIME = 'time';
const TIME_LAST_CHECK = 'time_last_check';
const ID_INTERSTITIAL = 'ca-app-pub-1303758337250441/3021692383';
const ID_REWARDED_INT = 'ca-app-pub-1303758337250441/5673574753';
const ID_APP = 'ca-app-pub-1303758337250441~3688477617';

const COUNTRY_TO_FLAG = {
  'afghanistan': '🇦🇫',
  'åland islands': '🇦🇽',
  'albania': '🇦🇱',
  'algeria': '🇩🇿',
  'american samoa': '🇦🇸',
  'andorra': '🇦🇩',
  'angola': '🇦🇴',
  'anguilla': '🇦🇮',
  'antarctica': '🇦🇶',
  'antigua and barbuda': '🇦🇬',
  'argentina': '🇦🇷',
  'armenia': '🇦🇲',
  'aruba': '🇦🇼',
  'australia': '🇦🇺',
  'austria': '🇦🇹',
  'azerbaijan': '🇦🇿',
  'bahamas': '🇧🇸',
  'bahrain': '🇧🇭',
  'bangladesh': '🇧🇩',
  'barbados': '🇧🇧',
  'belarus': '🇧🇾',
  'belgium': '🇧🇪',
  'belize': '🇧🇿',
  'benin': '🇧🇯',
  'Bermuda': '🇧🇲',
  'bhutan': '🇧🇹',
  'bolivia': '🇧🇴',
  'bosnia and herzegovina': '🇧🇦',
  'botswana': '🇧🇼',
  'bouvet island': '🇧🇻',
  'brazil': '🇧🇷',
  'british indian ocean territory': '🇮🇴',
  'brunei': '🇧🇳',
  'bulgaria': '🇧🇬',
  'burkina faso': '🇧🇫',
  'burundi': '🇧🇮',
  'cambodia': '🇰🇭',
  'cameroon': '🇨🇲',
  'canada': '🇨🇦',
  'cape verde': '🇨🇻',
  'caribbean netherlands': '🇧🇶',
  'cayman islands': '🇰🇾',
  'the central african republic': '🇨🇫',
  'chad': '🇹🇩',
  'chile': '🇨🇱',
  'china': '🇨🇳',
  'christmas island': '🇨🇽',
  'cocos islands': '🇨🇨',
  'colombia': '🇨🇴',
  'the comoros': '🇰🇲',
  'the republic of the congo': '🇨🇬',
  'the democratic republic of the congo': '🇨🇩',
  'cook islands': '🇨🇰',
  'costa rica': '🇨🇷',
  'cote d ivoire': '🇨🇮',
  'croatia': '🇭🇷',
  'cuba': '🇨🇺',
  'curacao': '🇨🇼',
  'cyprus': '🇨🇾',
  'the czech republic': '🇨🇿',
  'denmark': '🇩🇰',
  'djibouti': '🇩🇯',
  'dominica': '🇩🇲',
  'the dominican republic': '🇩🇴',
  'ecuador': '🇪🇨',
  'egypt': '🇪🇬',
  'el salvador': '🇸🇻',
  'england': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'equatorial guinea': '🇬🇶',
  'eritrea': '🇪🇷',
  'estonia': '🇪🇪',
  'swaziland': '🇸🇿',
  'ethiopia': '🇪🇹',
  'falkland islands': '🇫🇰',
  'faroe islands': '🇫🇴',
  'fiji': '🇫🇯',
  'finland': '🇫🇮',
  'france': '🇫🇷',
  'french guiana': '🇬🇫',
  'french polynesia': '🇵🇫',
  'french southern and antarctic lands': '🇹🇫',
  'gabon': '🇬🇦',
  'the gambia': '🇬🇲',
  'georgia': '🇬🇪',
  'germany': '🇩🇪',
  'ghana': '🇬🇭',
  'gibraltar': '🇬🇮',
  'greece': '🇬🇷',
  'greenland': '🇬🇱',
  'grenada': '🇬🇩',
  'guadeloupe': '🇬🇵',
  'guam': '🇬🇺',
  'guatemala': '🇬🇹',
  'guernsey': '🇬🇬',
  'guinea': '🇬🇳',
  'guinea bissau': '🇬🇼',
  'guyana': '🇬🇾',
  'haiti': '🇭🇹',
  'heard island and mcdonald islands': '🇭🇲',
  'honduras': '🇭🇳',
  'hong kong': '🇭🇰',
  'hungary': '🇭🇺',
  'iceland': '🇮🇸',
  'india': '🇮🇳',
  'indonesia': '🇮🇩',
  'iran': '🇮🇷',
  'iraq': '🇮🇶',
  'ireland': '🇮🇪',
  'isle of man': '🇮🇲',
  'israel': '🇮🇱',
  'italy': '🇮🇹',
  'jamaica': '🇯🇲',
  'japan': '🇯🇵',
  'jersey': '🇯🇪',
  'jordan': '🇯🇴',
  'kazakhstan': '🇰🇿',
  'kenya': '🇰🇪',
  'kiribati': '🇰🇮',
  'north korea': '🇰🇵',
  'south korea': '🇰🇷',
  'kosovo': '🇽🇰',
  'kuwait': '🇰🇼',
  'kyrgyzstan': '🇰🇬',
  'laos': '🇱🇦',
  'latvia': '🇱🇻',
  'lebanon': '🇱🇧',
  'lesotho': '🇱🇸',
  'liberia': '🇱🇷',
  'libya': '🇱🇾',
  'liechtenstein': '🇱🇮',
  'lithuania': '🇱🇹',
  'luxembourg': '🇱🇺',
  'macau': '🇲🇴',
  'madagascar': '🇲🇬',
  'malawi': '🇲🇼',
  'malaysia': '🇲🇾',
  'maldives': '🇲🇻',
  'mali': '🇲🇱',
  'malta': '🇲🇹',
  'the marshall islands': '🇲🇭',
  'martinique': '🇲🇶',
  'mauritania': '🇲🇷',
  'mauritius': '🇲🇺',
  'mayotte': '🇾🇹',
  'mexico': '🇲🇽',
  'micronesia': '🇫🇲',
  'moldova': '🇲🇩',
  'monaco': '🇲🇨',
  'mongolia': '🇲🇳',
  'montenegro': '🇲🇪',
  'montserrat': '🇲🇸',
  'morocco': '🇲🇦',
  'mozambique': '🇲🇿',
  'myanmar': '🇲🇲',
  'namibia': '🇳🇦',
  'nauru': '🇳🇷',
  'nepal': '🇳🇵',
  'the netherlands': '🇳🇱',
  'new caledonia': '🇳🇨',
  'new zealand': '🇳🇿',
  'nicaragua': '🇳🇮',
  'niger': '🇳🇪',
  'nigeria': '🇳🇬',
  'niue': '🇳🇺',
  'norfolk island': '🇳🇫',
  'macedonia': '🇲🇰',
  'northern mariana islands': '🇲🇵',
  'norway': '🇳🇴',
  'oman': '🇴🇲',
  'pakistan': '🇵🇰',
  'palau': '🇵🇼',
  'palestine': '🇵🇸',
  'panama': '🇵🇦',
  'papua new guinea': '🇵🇬',
  'paraguay': '🇵🇾',
  'peru': '🇵🇪',
  'the philippines': '🇵🇭',
  'pitcairn islands': '🇵🇳',
  'poland': '🇵🇱',
  'portugal': '🇵🇹',
  'puerto rico': '🇵🇷',
  'qatar': '🇶🇦',
  'reunion': '🇷🇪',
  'romania': '🇷🇴',
  'russia': '🇷🇺',
  'rwanda': '🇷🇼',
  'saint barthelemy': '🇧🇱',
  'saint helena ascension and tristan da cunha': '🇸🇭',
  'saint kitts and nevis': '🇰🇳',
  'saint lucia': '🇱🇨',
  'saint martin': '🇲🇫',
  'saint pierre and miquelon': '🇵🇲',
  'saint vincent and the grenadines': '🇻🇨',
  'samoa': '🇼🇸',
  'san marino': '🇸🇲',
  'sao tome and principe': '🇸🇹',
  'saudi arabia': '🇸🇦',
  'scotland': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'senegal': '🇸🇳',
  'serbia': '🇷🇸',
  'the seychelles': '🇸🇨',
  'sierra leone': '🇸🇱',
  'singapore': '🇸🇬',
  'sint maarten': '🇸🇽',
  'slovakia': '🇸🇰',
  'slovenia': '🇸🇮',
  'the solomon islands': '🇸🇧',
  'somalia': '🇸🇴',
  'south africa': '🇿🇦',
  'south georgia': '🇬🇸',
  'south sudan': '🇸🇸',
  'spain': '🇪🇸',
  'sri lanka': '🇱🇰',
  'sudan': '🇸🇩',
  'suriname': '🇸🇷',
  'svalbard and jan mayen': '🇸🇯',
  'sweden': '🇸🇪',
  'switzerland': '🇨🇭',
  'syria': '🇸🇾',
  'taiwan': '🇹🇼',
  'tajikistan': '🇹🇯',
  'tanzania': '🇹🇿',
  'thailand': '🇹🇭',
  'east timor': '🇹🇱',
  'togo': '🇹🇬',
  'tokelau': '🇹🇰',
  'tonga': '🇹🇴',
  'trinidad and tobago': '🇹🇹',
  'tunisia': '🇹🇳',
  'turkey': '🇹🇷',
  'turkmenistan': '🇹🇲',
  'turks and caicos islands': '🇹🇨',
  'tuvalu': '🇹🇻',
  'uganda': '🇺🇬',
  'ukraine': '🇺🇦',
  'the united arab emirates': '🇦🇪',
  'the united kingdom': '🇬🇧',
  'the united states': '🇺🇸',
  'united states minor outlying islands': '🇺🇲',
  'uruguay': '🇺🇾',
  'uzbekistan': '🇺🇿',
  'vanuatu': '🇻🇺',
  'the vatican city': '🇻🇦',
  'venezuela': '🇻🇪',
  'vietnam': '🇻🇳',
  'virgin islands (british)': '🇻🇬',
  'virgin islands (u.s.)': '🇻🇮',
  'wales': '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  'wallis and futuna': '🇼🇫',
  'western sahara': '🇪🇭',
  'yemen': '🇾🇪',
  'zambia': '🇿🇲',
  'zimbabwe': '🇿🇼'
};

const CODE_TO_COUNTRY = {
  'AF': "Afghanistan",
  'AL': "Albania",
  'DZ': "Algeria",
  'AS': "American Samoa",
  'AD': "Andorra",
  'AO': "Angola",
  'AI': "Anguilla",
  'AQ': "Antarctica",
  'AG': "Antigua and Barbuda",
  'AR': "Argentina",
  'AM': "Armenia",
  'AW': "Aruba",
  'AU': "Australia",
  'AT': "Austria",
  'AZ': "Azerbaijan",
  'BS': "Bahamas",
  'BH': "Bahrain",
  'BD': "Bangladesh",
  'BB': "Barbados",
  'BY': "Belarus",
  'BE': "Belgium",
  'BZ': "Belize",
  'BJ': "Benin",
  'BM': "Bermuda",
  'BT': "Bhutan",
  'BO': "Bolivia",
  'BQ': "Bonaire, Sint Eustatius and Saba",
  'BA': "Bosnia and Herzegovina",
  'BW': "Botswana",
  'BV': "Bouvet Island",
  'BR': "Brazil",
  'IO': "British Indian Ocean Territory",
  'BN': "Brunei Darussalam",
  'BG': "Bulgaria",
  'BF': "Burkina Faso",
  'BI': "Burundi",
  'CV': "Cabo Verde",
  'KH': "Cambodia",
  'CM': "Cameroon",
  'CA': "Canada",
  'KY': "Cayman Islands (the)",
  'CF': "Central African Republic (the)",
  'TD': "Chad",
  'CL': "Chile",
  'CN': "China",
  'CX': "Christmas Island",
  'CC': "Cocos (Keeling) Islands (the)",
  'CO': "Colombia",
  'KM': "Comoros (the)",
  'CD': "Congo (the Democratic Republic of the)",
  'CG': "Congo (the)",
  'CK': "Cook Islands (the)",
  'CR': "Costa Rica",
  'HR': "Croatia",
  'CU': "Cuba",
  'CW': "Curaçao",
  'CY': "Cyprus",
  'CZ': "Czechia",
  'CI': "Côte d'Ivoire",
  'DK': "Denmark",
  'DJ': "Djibouti",
  'DM': "Dominica",
  'DO': "Dominican Republic (the)",
  'EC': "Ecuador",
  'EG': "Egypt",
  'SV': "El Salvador",
  'GQ': "Equatorial Guinea",
  'ER': "Eritrea",
  'EE': "Estonia",
  'SZ': "Eswatini",
  'ET': "Ethiopia",
  'FK': "Falkland Islands",
  'FO': "Faroe Islands",
  'FJ': "Fiji",
  'FI': "Finland",
  'FR': "France",
  'GF': "French Guiana",
  'PF': "French Polynesia",
  'TF': "French Southern Territories (the)",
  'GA': "Gabon",
  'GM': "Gambia (the)",
  'GE': "Georgia",
  'DE': "Germany",
  'GH': "Ghana",
  'GI': "Gibraltar",
  'GR': "Greece",
  'GL': "Greenland",
  'GD': "Grenada",
  'GP': "Guadeloupe",
  'GU': "Guam",
  'GT': "Guatemala",
  'GG': "Guernsey",
  'GN': "Guinea",
  'GW': "Guinea Bissau",
  'GY': "Guyana",
  'HT': "Haiti",
  'HM': "Heard Island and McDonald Islands",
  'VA': "Holy See (the)",
  'HN': "Honduras",
  'HK': "Hong Kong",
  'HU': "Hungary",
  'IS': "Iceland",
  'IN': "India",
  'ID': "Indonesia",
  'IR': "Iran (Islamic Republic of)",
  'IQ': "Iraq",
  'IE': "Ireland",
  'IM': "Isle of Man",
  'IL': "Israel",
  'IT': "Italy",
  'JM': "Jamaica",
  'JP': "Japan",
  'JE': "Jersey",
  'JO': "Jordan",
  'KZ': "Kazakhstan",
  'KE': "Kenya",
  'KI': "Kiribati",
  'KP': "Korea (the Democratic People's Republic of)",
  'KR': "Korea (the Republic of)",
  'KW': "Kuwait",
  'KG': "Kyrgyzstan",
  'LA': "Lao People's Democratic Republic (the)",
  'LV': "Latvia",
  'LB': "Lebanon",
  'LS': "Lesotho",
  'LR': "Liberia",
  'LY': "Libya",
  'LI': "Liechtenstein",
  'LT': "Lithuania",
  'LU': "Luxembourg",
  'MO': "Macao",
  'MG': "Madagascar",
  'MW': "Malawi",
  'MY': "Malaysia",
  'MV': "Maldives",
  'ML': "Mali",
  'MT': "Malta",
  'MH': "Marshall Islands (the)",
  'MQ': "Martinique",
  'MR': "Mauritania",
  'MU': "Mauritius",
  'YT': "Mayotte",
  'MX': "Mexico",
  'FM': "Micronesia (Federated States of)",
  'MD': "Moldova (the Republic of)",
  'MC': "Monaco",
  'MN': "Mongolia",
  'ME': "Montenegro",
  'MS': "Montserrat",
  'MA': "Morocco",
  'MZ': "Mozambique",
  'MM': "Myanmar",
  'NA': "Namibia",
  'NR': "Nauru",
  'NP': "Nepal",
  'NL': "Netherlands (the)",
  'NC': "New Caledonia",
  'NZ': "New Zealand",
  'NI': "Nicaragua",
  'NE': "Niger (the)",
  'NG': "Nigeria",
  'NU': "Niue",
  'NF': "Norfolk Island",
  'MP': "Northern Mariana Islands (the)",
  'NO': "Norway",
  'OM': "Oman",
  'PK': "Pakistan",
  'PW': "Palau",
  'PS': "Palestine, State of",
  'PA': "Panama",
  'PG': "Papua New Guinea",
  'PY': "Paraguay",
  'PE': "Peru",
  'PH': "Philippines (the)",
  'PN': "Pitcairn",
  'PL': "Poland",
  'PT': "Portugal",
  'PR': "Puerto Rico",
  'QA': "Qatar",
  'MK': "Republic of North Macedonia",
  'RO': "Romania",
  'RU': "Russian Federation (the)",
  'RW': "Rwanda",
  'RE': "Réunion",
  'BL': "Saint Barthélemy",
  'SH': "Saint Helena, Ascension and Tristan da Cunha",
  'KN': "Saint Kitts and Nevis",
  'LC': "Saint Lucia",
  'MF': "Saint Martin (French part)",
  'PM': "Saint Pierre and Miquelon",
  'VC': "Saint Vincent and the Grenadines",
  'WS': "Samoa",
  'SM': "San Marino",
  'ST': "Sao Tome and Principe",
  'SA': "Saudi Arabia",
  'SN': "Senegal",
  'RS': "Serbia",
  'SC': "Seychelles",
  'SL': "Sierra Leone",
  'SG': "Singapore",
  'SX': "Sint Maarten",
  'SK': "Slovakia",
  'SI': "Slovenia",
  'SB': "Solomon Islands",
  'SO': "Somalia",
  'ZA': "South Africa",
  'GS': "South Georgia and the South Sandwich Islands",
  'SS': "South Sudan",
  'ES': "Spain",
  'LK': "Sri Lanka",
  'SD': "Sudan (the)",
  'SR': "Suriname",
  'SJ': "Svalbard and Jan Mayen",
  'SE': "Sweden",
  'CH': "Switzerland",
  'SY': "Syrian Arab Republic",
  'TW': "Taiwan",
  'TJ': "Tajikistan",
  'TZ': "Tanzania, United Republic of",
  'TH': "Thailand",
  'TL': "Timor Leste",
  'TG': "Togo",
  'TK': "Tokelau",
  'TO': "Tonga",
  'TT': "Trinidad and Tobago",
  'TN': "Tunisia",
  'TR': "Turkey",
  'TM': "Turkmenistan",
  'TC': "Turks and Caicos Islands (the)",
  'TV': "Tuvalu",
  'UG': "Uganda",
  'UA': "Ukraine",
  'AE': "United Arab Emirates (the)",
  'GB': "United Kingdom of Great Britain and Northern Ireland (the)",
  'UM': "United States Minor Outlying Islands (the)",
  'US': "United States of America (the)",
  'UY': "Uruguay",
  'UZ': "Uzbekistan",
  'VU': "Vanuatu",
  'VE': "Venezuela",
  'VN': "Viet Nam",
  'VG': "Virgin Islands (British)",
  'VI': "Virgin Islands (U.S.)",
  'WF': "Wallis and Futuna",
  'EH': "Western Sahara",
  'YE': "Yemen",
  'ZM': "Zambia",
  'ZW': "Zimbabwe",
  'AX': "Åland Islands"
};

appLog(tag, msg) => print('$tag:$msg');
//Test country to flag, last: Afghanistan
